export const importedTransactions = [
  {
    id: "seed-1",
    type: "income",
    amount: 3200000,
    category: "월급",
    member: "jw",
    account: "bank-transfer",
    date: "2026-04-10",
    note: "4월 급여",
  },
  {
    id: "seed-2",
    type: "income",
    amount: 2800000,
    category: "월급",
    member: "partner",
    account: "bank-transfer",
    date: "2026-04-10",
    note: "예비신부 급여",
  },
  {
    id: "seed-3",
    type: "expense",
    amount: 149740,
    category: "집세",
    member: "jw",
    account: "credit-card",
    date: "2026-04-01",
    note: "관리비",
  },
  {
    id: "seed-4",
    type: "expense",
    amount: 14200,
    category: "식비",
    member: "jw",
    account: "debit-card",
    date: "2026-04-03",
    note: "카페인중독 두바이",
  },
  {
    id: "seed-5",
    type: "expense",
    amount: 34819,
    category: "의료/건강",
    member: "jw",
    account: "debit-card",
    date: "2026-04-06",
    note: "닥터나우 인공눈물",
  },
  {
    id: "seed-6",
    type: "expense",
    amount: 120000,
    category: "선물",
    member: "partner",
    account: "credit-card",
    date: "2026-04-09",
    note: "기념일 선물",
  },
  {
    id: "seed-7",
    type: "expense",
    amount: 54000,
    category: "교통비",
    member: "jw",
    account: "cash",
    date: "2026-04-12",
    note: "택시 및 주차",
  },
  {
    id: "seed-8",
    type: "expense",
    amount: 98000,
    category: "문화생활",
    member: "partner",
    account: "debit-card",
    date: "2026-04-18",
    note: "주말 데이트",
  },
  {
    id: "seed-9",
    type: "expense",
    amount: 67000,
    category: "생필품",
    member: "jw",
    account: "credit-card",
    date: "2026-04-18",
    note: "생활용품 구매",
  },
  {
    id: "seed-10",
    type: "transfer",
    amount: 500000,
    category: "저축",
    member: "jw",
    account: "bank-transfer",
    date: "2026-04-20",
    note: "공동 적금 이체",
  },
];
